export const mockCases = [
  {
    id: "CAS-10492",
    patient: "John Doe",
    client: "Downtown Dental Studio",
    type: "Crown & Bridge",
    status: "Processing",
    date: "Oct 24, 2026",
  },
  {
    id: "CAS-10491",
    patient: "Emma Collins",
    client: "Smile Care Orthodontics",
    type: "Aligners",
    status: "Review",
    date: "Oct 23, 2026",
  },
  {
    id: "CAS-10490",
    patient: "Michael Chang",
    client: "Westside Implant Center",
    type: "Implant",
    status: "Completed",
    date: "Oct 22, 2026",
  },
  {
    id: "CAS-10489",
    patient: "Sarah Jenkins",
    client: "Downtown Dental Studio",
    type: "Denture",
    status: "Processing",
    date: "Oct 22, 2026",
  },
  {
    id: "CAS-10488",
    patient: "Robert Smith",
    client: "Smile Care Orthodontics",
    type: "Crown & Bridge",
    status: "Shipped",
    date: "Oct 21, 2026",
  },
  {
    id: "CAS-10487",
    patient: "Alice Johnson",
    client: "Lakeside Dental Arts",
    type: "Implant",
    status: "Processing",
    date: "Oct 20, 2026",
  },
  {
    id: "CAS-10486",
    patient: "David Miller",
    client: "Bright Smiles Kids",
    type: "Aligners",
    status: "Completed",
    date: "Oct 19, 2026",
  },
  {
    id: "CAS-10485",
    patient: "Nancy Davis",
    client: "Premier Dental Group",
    type: "Denture",
    status: "Review",
    date: "Oct 18, 2026",
  },
  {
    id: "CAS-10484",
    patient: "James Taylor",
    client: "Westside Implant Center",
    type: "Crown & Bridge",
    status: "Shipped",
    date: "Oct 17, 2026",
  },
  {
    id: "CAS-10483",
    patient: "Patricia Wilson",
    client: "Lakeside Dental Arts",
    type: "Implant",
    status: "Processing",
    date: "Oct 16, 2026",
  },
];

export const mockClients = [
  {
    name: "Downtown Dental Studio",
    dentist: "Dr. Michael Chen",
    cases: 24,
    status: "Active",
    location: "New York, NY",
  },
  {
    name: "Smile Care Orthodontics",
    dentist: "Dr. Sarah Smith",
    cases: 18,
    status: "Active",
    location: "Brooklyn, NY",
  },
  {
    name: "Westside Implant Center",
    dentist: "Dr. James Wilson",
    cases: 12,
    status: "Active",
    location: "Newark, NJ",
  },
  {
    name: "Bright Smiles Kids",
    dentist: "Dr. Emily Davis",
    cases: 5,
    status: "Active",
    location: "Queens, NY",
  },
  {
    name: "Premier Dental Group",
    dentist: "Dr. Robert Taylor",
    cases: 0,
    status: "Inactive",
    location: "Jersey City, NJ",
  },
  {
    name: "Lakeside Dental Arts",
    dentist: "Dr. Amanda Brown",
    cases: 31,
    status: "Active",
    location: "White Plains, NY",
  },
  {
    name: "Coastal Dental Care",
    dentist: "Dr. Steven White",
    cases: 8,
    status: "Active",
    location: "Long Beach, NY",
  },
  {
    name: "Summit Ortho",
    dentist: "Dr. Lisa Green",
    cases: 15,
    status: "Pending",
    location: "Staten Island, NY",
  },
];

export const mockAnalytics = {
  metrics: [
    { label: "Total Revenue", value: "$84,240", change: "+12.5%", isUp: true },
    { label: "Completed Cases", value: "432", change: "+5.2%", isUp: true },
    {
      label: "Avg Turnaround",
      value: "3.2 days",
      change: "-8.1%",
      isUp: false,
    },
    { label: "Remake Rate", value: "1.4%", change: "-0.3%", isUp: false },
  ],
  revenueChart: [40, 60, 45, 80, 55, 90, 75, 100, 85, 95, 70, 110], // Jan -> Dec
  products: [
    { name: "Crown & Bridge", val: 45, color: "bg-blue-500" },
    { name: "Aligners", val: 30, color: "bg-purple-500" },
    { name: "Implants", val: 15, color: "bg-emerald-500" },
    { name: "Dentures", val: 10, color: "bg-amber-500" },
  ],
};
